name: Build and Deploy
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          activate-conda: true
          conda-channels: anaconda, conda-forge
          
      - name: Install required dependencies
        run: |
          conda install -c conda-forge graph-tool
          pip install Sphinx
          git clone https://github.com/potassco/clorm
          cd clorm
          pip install .
          cd ..
          python3 setup.py install
          ls
          pip install sphinx-copybutton
          pip install furo
          pip install wheel
          pip install twine

      - name: Build HTML files   
        run: |
          cd sphinx-build
          make clean html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: sphinx-build/_build/html
          target-folder: docs


      - name: Publish to Pypi
        run: |  
          git stash
          git fetch --all
          git checkout version
          bash version_update.sh
          cat version.py
          python3 setup.py sdist bdist_wheel
          twine upload dist/* -u ${{secrets.PYPI_USER}} -p ${{secrets.PYPI_PASSWORD}}
